fix(android)!: access Context through webView.getContext()
apache/cordova-plugin-device pull request #200
Opened 2024-05-14 09:03 UTC by erisu

### Platforms affected

android

### Motivation and Context

closes #62 
closes CB-12623

### Description

Applied same change. Unable to cherry-pick original authors commit as the repo has been removed.

### Testing

n/a

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

2024-05-14 13:40 UTC, breautek approved these changes

2024-05-14 19:41 UTC, jcesarmobile commented
I managed to get the user commit 
https://github.com/apache/cordova-plugin-device/pull/201

2024-05-14 19:46 UTC, jcesarmobile requested changes
engines also need to be set in the plugin.xml

https://github.com/apache/cordova-plugin-device/blob/master/plugin.xml#L34

2024-05-15 01:40 UTC, breautek approved these changes

2024-05-15 07:47 UTC, jcesarmobile approved these changes

2024-05-31 14:06 UTC, merged